apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/backend"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2022-11-26T18:10:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"c8fdb7e3-cf53-4565-b5eb-96168803a7a3"}: {}
      f:spec:
        f:internalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: rancher
    operation: Update
    time: "2022-11-26T18:10:35Z"
  name: backend
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: backend
    uid: c8fdb7e3-cf53-4565-b5eb-96168803a7a3
  resourceVersion: "29035"
  uid: 7b404690-05c6-49ab-b260-359599f3f055
spec:
  clusterIP: 10.43.192.2
  clusterIPs:
  - 10.43.192.2
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ss-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-backend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
