apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://ec2-35-170-55-126.compute-1.amazonaws.com/k8s/clusters/local"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      FkyT1RRNApNalEzT1RBZUZ3MHlNakV4TWpZeE56QTNOVGxhRncwek1qRXhNak14TnpBM05UbGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qWTVORGd5TkRjNU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRU5PTnZhTUVuaUZ5bQp6WFJ1WVhjMjU5ZUFoYTl3YmtQNHhrZHluM\
      zlQMm91RTFyb2E5eldCQmNCQy9Jb2dkTElZc0s0dHJLVzloUEZtCmRVUlNTbEVERzZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      VIveTcrU28rcmxHcWdaZSs3S055R0pianQ4TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSURjbApYM\
      kpFVURNTi9jdXNTRkVPY3dDQTI5L2hQbjNPQzhCd2lVT1FzR1BDQWlFQW15dUk1VkpYVkxoMXR6Z\
      TVrRlRZCmpPUk9BS0RFZUN5aW5DaytPOTJsM1NFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "local"
  user:
    token: "kubeconfig-user-2tpcgnf6qv:mtkfcg24dz5g96njjx8kf2j2p5glg2gtbjwzdr5kqvr59rld7fgk4h"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
